### ISSUE TITLE
bash: dnvm: command not found

### ISSUE THREAD

**Issue by jwulf** [mgolisch/dnvm-fish#1]
```
 /u/l/C/d/1.0.0-dev   master ±  dnvm
bash: dnvm: command not found
```

It's running the function, because `bash` is throwing the error. If I shell to `bash` and then source `dnvm` it works.

**Comment by jwulf** [comment]
I added `source` - that fixed it (I'm also using the homebrew location):

```
function dnvm --description "wraps the dnvm.sh bash script"
        bash -c "source /usr/local/bin/dnvm.sh && dnvm $argv"
end
```

**Comment by mgolisch** [comment]
it now should check for the homebrew location too.
