### ISSUE TITLE
filename argument required

### ISSUE THREAD

**Issue by weiran** [mgolisch/dnvm-fish#2]
I'm getting an error: 

```
weiran@big-mac ~> dnvm
bash: line 0: .: filename argument required
.: usage: . filename [arguments]
```

Any ideas?

**Comment by mgolisch** [comment]
yes,  dnvm.sh is not found in either:  ~/.dnx/dnvm/dnvm.sh or /usr/local/bin/dnvm.sh

**Comment by weiran** [comment]
Mine is located at `/usr/local/lib/dnx/bin/dnvm.sh`, I wonder if this is this a recent change.
